# ref: http://ss64.com/osx/ls.html
# Long form no user group, color
alias l="ls -oG"

# Order by last modified, long form no user group, color
alias lt="ls -toG"

# List all except . and ..., color, mark file types, long form no user group, file size
alias la="ls -AGFoh"

# List all except . and ..., color, mark file types, long form no use group, order by last modified, file size
alias lat="ls -AGFoth"

# Concatenate and print content of files (add line numbers)
alias catn="cat -n"

# IP addresses
alias ip1="ipconfig getifaddr en0"
alias ip2="ipconfig getifaddr en1"

# Copy my public key to the pasteboard
alias pubkey="more ~/.ssh/$1.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# Flush DNS cache
alias flushdns="dscacheutil -flushcache"

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias clearlogs="sudo rm -rfv /private/var/log/asl/*.asl"
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; clearlogs"

# Dev helpers
alias killnode="killall node"

# Shortcuts
alias selenium="selenium-standalone start --version=2.46.0 --drivers.chrome.version=2.16"
alias redis="redis28-server"
