# Defaults: https://github.com/ianyh/Amethyst/issues/1321

# Use tall and fullscreen layouts
layouts:
  - tall
  - tall-right
  - fullscreen
  - two-pane
  - bsp

# Modify the amethyst relaunch to use x and not z
relaunch-amethyst:
  mod: mod2
  key: x

# Enable focus-follows-mouse
mouse-follows-focus: false
focus-follows-mouse: false

# Manual sort of windows
mouse-swaps-windows: true

# Mouse Resize
mouse-resizes-windows: true

# Add 16px margin between windows
window-margins: true
window-margin-size: 16

# Key Bindings
# ------------

# Move to the next layout in the list.
cycle-layout:
  mod: mod1
  key: "space"

# Move to the previous layout in the list.
cycle-layout-backward:
  mod: mod2
  key: "space"

# Shrink the main pane by a percentage of the screen dimension as defined by window-resize-step. Note that not all layouts respond to this command.
shrink-main:
  mod: mod1
  key: h

# Expand the main pane by a percentage of the screen dimension as defined by window-resize-step. Note that not all layouts respond to this command.
expand-main:
  mod: mod1
  key: l

# Focus the main window in the list.
focus-main:
  mod: mod1
  key: m

# Focus the next window in the list going clockwise.
focus-cw:
  mod: mod1
  key: k

# Focus the next window in the list going counter-clockwise.
focus-ccw:
  mod: mod1
  key: j

# Swap the position of the currently focused window with the main window in the list.
swap-main:
  mod: mod1
  key: "enter"

# Rerun the current layout's algorithm.
reevaluate-windows:
  mod: mod1
  key: z

# Turn on or off tiling entirely.
toggle-tiling:
  mod: mod1
  key: t

# List of bundle identifiers for applications to either be automatically floating or automatically tiled based on floating-is-blacklist (default []).
floating: ["com.apple.systempreferences"]
