# Defaults: https://github.com/ianyh/Amethyst/issues/1321

# Move this file to: `~/.amethyst.yml`
# In order to register changes restart Amethyst.
# If you experience issues pulling in the changes you can also quit Amethyst and run: `rm ~/Library/Preferences/com.amethyst.Amethyst.plist`
# This removes the current preferences and causes a re-load of this file when amethyst restarts.

layouts:
  - fullscreen
  - two-pane
  - bsp
  - wide
  - tall

mod1:
  - option
  - shift
  - control
  - command

mod2:
  - option
  - shift
  - control

# Move to the next layout in the list.
cycle-layout:
  mod: mod1
  key: "space"

# Move to the previous layout in the list.
cycle-layout-backward:
  mod: mod2
  key: "space"

# Shrink the main pane by a percentage of the screen dimension as defined by window-resize-step. Note that not all layouts respond to this command.
shrink-main:
  mod: mod1
  key: h

# Expand the main pane by a percentage of the screen dimension as defined by window-resize-step. Note that not all layouts respond to this command.
expand-main:
  mod: mod1
  key: l

# Focus the next window in the list going counter-clockwise.
focus-ccw:
  mod: mod1
  key: j

# Focus the next window in the list going clockwise.
focus-cw:
  mod: mod1
  key: k

# Focus the main window in the list.
focus-main:
  mod: mod1
  key: m

# Swap the position of the currently focused window with the next window in the list going counter-clockwise.
swap-ccw:
  mod: mod2
  key: j

# Swap the position of the currently focused window with the next window in the list going clockwise.
swap-cw:
  mod: mod2
  key: k

# Swap the position of the currently focused window with the main window in the list.
swap-main:
  mod: mod1
  key: "enter"

throw-space-1:
  mod: mod1
  key: "1"

throw-space-2:
  mod: mod1
  key: "2"

throw-space-3:
  mod: mod1
  key: "3"

throw-space-4:
  mod: mod1
  key: "4"

throw-space-5:
  mod: mod1
  key: "5"

# Rerun the current layout's algorithm.
reevaluate-windows:
  mod: mod1
  key: z

window-margins: true
smart-window-margins: false
window-margin-size: 16

floating:
  [
    "com.apple.systempreferences",
    "com.1password.1password",
    "com.raycast.macos",
    "ee.clockwise.gmask",
    "com.apple.calculator",
    "com.authy.authy-mac",
  ]

floating-is-blacklist: true
float-small-windows: true

mouse-follows-focus: false
focus-follows-mouse: false
mouse-swaps-windows: true
mouse-resizes-windows: true

enables-layout-hud: true
enables-layout-hud-on-space-change: true

new-windows-to-main: false
follow-space-thrown-windows: true

window-resize-step: 5
restore-layouts-on-launch: true
